### ISSUE TITLE
Data-linking to functions and helper functions

### ISSUE THREAD

**Issue by govis** [BorisMoore/jsviews#100]
Hi Boris

I am trying to data-link to a function as follows:

```
Visible: function(visible) {
    if(visible != undefined) {
        this.$visible = visible;
        //some other logic
        return;
    }
    return this.$visible;
}
```

```
data-link="css-display{:~visible2Css(nestedPath.Visible)}"
```

Skimming through the code for jquery.observable.js I can see that it seems to supports functions too. 

However I noticed that when the helper function (visible2Css) is called, it gets the function itself passed to it as opposed to the actual value returned by the getter. In case when the function is an instance method of some other object it may cause a problem as it also requires the object instance context, which I guess could be passed in as another parameter, but I think it would be much simpler if jsView called the getter and passed in its' returned value instead.

What do you think?

Thanks.

**Comment by larjohn** [comment]
Regarding Computed helper setters, in the sampe, the text (https://github.com/BorisMoore/jsviews/blob/master/demos/features/observability/computed-helper.html) shows:

```javascript
fullName.set = function(val) {
    $.observable(this).setProperty({
        lastName: ...,
        firstName: ...
    });
```

while the actual source code is:

```javascript
fullName.set = function(val) {
	val = val.split(" ");
	$.observable(person).setProperty({
		lastName: val.pop(),
		firstName: val.join(" ")
	});
};
```

In the function's context this returns a function, while it is assumed to return the data-bound object. I could access the object using

$.view(this()).views["_1"].data

But it seems ugly to me, and I was wondering if it was accessible in some other way.

**Comment by BorisMoore** [comment]
Yes, you are right, that was incorrectly copied from the other example: https://github.com/BorisMoore/jsviews/blob/master/demos/features/observability/computed-data.html#L146

For better encapsulation you may want to follow a ViewModel approach as in https://github.com/BorisMoore/jsviews/blob/master/demos/features/observability/computed-data.html or https://github.com/BorisMoore/jsviews/blob/master/demos/features/observability/computed-data-prototype.html - see also http://www.jsviews.com/#explore/objectsorvm.

Meantime - if you want to use the getter setter approach with a ~fullName() helper, not a ViewModel, then you access the view and the data slightly more cleanly like this"

`var view = $.view().get(true, "data");`

(`$.view()` is the top-level view. `$.view().get(true, "data")` is the first child view of type "data".

However even that would not work if you had more than one container element in the page that you were linking a template to - and if your was the second one, not the first.

So I will update the JsViews implementation in the next update, so that the `this` pointer of the setter on both the `fullName` function itself, and the setter, will be the `view`. I'll probably create a new issue to track this. Also I will add a simpler API to get the first child view of any type: `view.get(true)`
