### ISSUE TITLE
Issue with ajax request

### ISSUE THREAD

**Issue by gbouthenot** [BorisMoore/jsviews#239]
I created a very simple jsfiddle here
http://jsfiddle.net/gbouthenot/Y5TTL/

``` html
<script id="targTmpl" type="text/x-jsrender">
  {^{for #data}}
    <li>
      <input type='text' data-link="int" />
    </li>
  {{/for}}
</script>

<ul id="targ"></ul>
<button class="btn">test</button>
```

``` javascript
window.fields = [ {int:"int1"}, {int:"int2"} ];
$.templates("#targTmpl").link("#targ", window.fields);

$(".btn").on("click", function(){
    console.log(fields); // has a jQuery object. Why ??
    $.ajax({url:'', method:'post', data: {fields:window.fields}, complete:function(){
        alert("complete");
    }});
});
```

The problem is that I am not able to submit a form with an ajax request. The code throws an obscure `Uncaught TypeError: Cannot read property 'data' of undefined in jsviews.js:1672` (in onObservableChange()).
Why onObservableChange() is called (without parameters, hence the error) ?

I noticed that once I call $.template, the original fields is enhanced with a jQuery object, and when the ajax call occurs, it cannot get the expected values.
I tried to modify the ajax settings parameters:
`data: {fields:$.observable(window.fields).data()}` to get only the values without the embedded jQuery object, but it didn't work.

Thank for your help.

**Comment by BorisMoore** [comment]
With jQuery2.*.js works correctly, since the `$(myData).on()` adds a `myData[$.expando]` property which is non-enumerable - using `Object.defineProperties( owner, descriptor );`

But with jQuery1.*.js it adds the expando using `cache[ id ] = isNode ? {} : { toJSON: jQuery.noop };`

and although this is not serialized by `JSON.stringify(), it **is** serialized by `buildParams`:

```js
	} else if ( !traditional && jQuery.type( obj ) === "object") {
		// Serialize object item.
		for ( name in obj ) {
			buildParams( prefix + "[" + name + "]", obj[ name ], traditional, add );
		}
```

- and as a result the ajax post call will parse the expando, and hence the events - and finish by calling methods on the data object...

A suggested fix is to write

```js
 	} else if ( !traditional && jQuery.type( obj ) === "object" && (!obj.toJSON || obj.toJSON())) {
```

I have not yet submitted a bug report to jQuery. I'll look at doing so.
