### ISSUE TITLE
Can a template have a child script tag ?

### ISSUE THREAD

**Issue by Avinava** [BorisMoore/jsviews#242]
Well I know this is a kind of weird question but was just curious if by any means we can have a script tag inside a template ? Currently it throws errors.  Well the use case is I am developing a app on Force.com and some inbuilt Force.com VF components insert script tag in the page(in my case template).

Is there is a way to make this work ?

something like

```
<script type="text/x-jsrender">
    <!-- Some HTML --->
   <script>
        <!-- Some JS Function --->
   </script>
</script>
```

**Comment by kashirin-alex** [comment]
Hello,
something similar to nested script tag in a template,
 if the script tag is a var data for including with innerHTML,
the issue is jsRender is working while jsView is not executing the tag,

examples as test-env,
**jsRender case (works)**:
  https://www.jsviews.com/#samples/data-link/from-render-to-link
  to people add 
      code: "<script>alert('js executed');</script>",
  and html template loop added with 
        {{:code}} 

while the same to **jsView with .link ( not working)**
the first example , https://www.jsviews.com/#linked-tag-syntax
add to members: 
    {name: "<script>alert('js executed');</script>"},
it does not run while the script tag is set in the html but it won't be executed.


What can be the cause?   The allowCode/executeCode {{* }}, in a case, is less preferred to work with

Thank you,
Kashirin Alex

**Comment by BorisMoore** [comment]
It sounds like a bad idea to me to insert script tags and try to make them run. The behavior may be browser dependent, and may also occur more than once if JsViews refreshes content more than once, in some scenarios. If you really need code to run (and are ready to deal with side-effects and possibly needing to deal with processing model questions that might affect the order of execution, then OK - but I would recommend allowCode rather than raw script tags. 
Why is allowCode less preferred for you?

**Comment by kashirin-alex** [comment]
the refresh case would been an issue, in case the code did execute.

it is for a case when it is script tag for inclusion and to make a template for each type might be less preferred.
current solution is   
for an ad in this case I have done get the view.data and do the innerHTML
   https://thither.direct/static/jsviews/ecuts/jstags.js
for the template
   https://thither.direct/static/jsviews/templates/datatypes/catalogue/ads/datatypes_catalogue_ads.tmpl

Thanks
