### ISSUE TITLE
request for {for-else} support in "data-link"

### ISSUE THREAD

**Issue by eugene-panferov** [BorisMoore/jsviews#293]
for the sake of uniformity of my data-linked tags i wanted to use 
{for} WITH {else} inside the "data-link" attribute.

**Comment by BorisMoore** [comment]
Eugene and I had some additional email exchanges on this, as follows:

_**From Boris**_
`<div data-link="{for Players tmpl='#player' else='#noplayer'}">` is not supported currently. 

You can write:

`<div>{^{for Players tmpl='#player'}}{{else tmpl='#noplayer'}}{{/for}}<div>`

I am considering adding support for the following syntax:

`<div data-link="{for Players tmpl='#player'}{else tmpl='#noplayer'}">`

Note that currently `<div data-link="title{for Players tmpl='#player'}">` will not work for other targets, such as title. 

Is there any scenario where `<div>{^{for Players tmpl='#player'}}{{else tmpl='#noplayer'}}{{/for}}<div>` will not work for you?

_**From Eugene**_

Is there any scenario where `<div>{^{for Players tmpl='#player'}}{{else
tmpl='#noplayer'}}{{/for}}<div>` will not work for you?

no, not really.
i just wanted my data-linked tags to be uniform.

since it will not work for other targets, such as title:

`<div data-link="title{for Players tmpl='#player'}{else tmpl='#noplayer'}">`

it is interesting problem indeed,
but it exists regardless of {else}
{for} itself is meaningless for almost every target but "html" and "text",
however, i can imagine a meaningful "title" attribute like the following:

`<character name="James Bond" title="he was killed in episodes: 3, 16, 17, 19, 27." />`

here {for} could be used for constructing planar representation of the episode array.

on the other hand,
not every (syntactically correct) combination of language's entities should be meaningful -- it is normal, you are not obliged to make stupid patterns syntactically impossible, otherwise it could be the greatest revolution in IT since von Neumann.


regarding particular syntax of the
`{for Players tmpl='#player'}{else tmpl='#noplayer'}`

i understand that the {else} is an entity in its own right, still

`{for Players tmpl='#player' else='#noplayer'}`

looks a bit more coherent, as it denotes the explicit relation between the {for} itself and its branches.

it is, of course, a merely question of style, either way i am going to use it, for some stronger reasons than a textual cuteness.

but

cycles in general have an intrinsic problem which most illustriously manifests in web applications.
cut the long story short, in all those "to-text" transformations the first and the last entries are special which causes code to get ugly (even if the difference is merely an absence of a delimiter after the last entry) unless we have a cycle with the exit statement in the middle.

maybe, it will be useful to extend {for} with few additional template references, such as:
- template that prepends all entries
- template of an entry
- template of the last entry
- template that replaces everything when no entries
- and (i am not sure) odd/even entry templates

so that we have *TYPICAL* {if{for}} combination codified as a whole

examples:
- `{for Players head="#caption" tmpl='#player' empty='#caption_empty'}`
- `{for Players tmpl='#player' tmpl_last='#player_last'}`

_**From Boris**_
OK - thanks for your thinking on this.

I am working on updates which add support for using data-linking with tags like {{for}} and {{if}} with targets like `title{` or `css-background-color{` etc.

So `title="he was killed in episodes: 3 16 17 19 27 "` can be achieved with `data-link="title{for episodes '#forTmpl'}"` using the template `{{if !index}}he was killed in episodes{{/if}} {{if killed}}{{:#index}}{{/if}}`

The reason for the syntax {tag ...}{else ...} is so as to support multiple elses, possibly with different expressions, as in the case of {{if}} where {{else}} is used as else if as well as the final else:

`{if expr1 tmpl='#ifTmpl'}{else expr2  tmpl='#else2Tmpl'}{else expr3  tmpl='#else3Tmpl'}{else tmpl='#noneTmpl'}` 

which  mirrors the corresponding syntax: `{^{if expr1 tmpl='#ifTmpl'}}{{else expr2  tmpl='#else2Tmpl'}}{{else expr3  tmpl='#else3Tmpl'}}{{else tmpl='#noneTmpl'}}{{/if}}` 

You can achieve the `{for Players head="#caption" tmpl='#player' empty='#caption_empty'}` scenario using `{for Players tmpl='#player'}{else tmpl='#caption_empty'}` where the #player template includes the header #caption block: `{{if !index tmpl='#caption'/}}`. Similarly for things like odd/even entry templates...

_**From Eugene**_

On 01/19/2015 01:53 AM, Boris Moore wrote:
> The reason for the syntax {tag ...}{else ...} is so as to support multiple
> elses, possibly with different expressions, as in the case of {{if}} where
> {{else}} is used as *else if *as well as the final *else*:

> *{if expr1 tmpl='#ifTmpl'}{else expr2  tmpl='#else2Tmpl'}{else expr3
>   tmpl='#else3Tmpl'}{else tmpl='#noneTmpl'}*

indeed, multiple branching is very important, although i failed to recognize "elseif" in the "else" at first glance.


> which  mirrors the corresponding syntax: `{^{if expr1
tmpl='#ifTmpl'}}{{else expr2  tmpl='#else2Tmpl'}}{{else expr3
tmpl='#else3Tmpl'}}{{else tmpl='#noneTmpl'}}{{/if}}`

it this particular snippet what confuses me is that syntactically/visually every "else" appears an entity of the same rank as "if" (which is not true), i have even missed the closing "/if" for several subsequent reading attempts.

if it is possible, i beg you, please, avoid HTML-like quasi-parenthesis constructed of individual tags that have a meaning of braces.

i am afraid i do not understand the exact reason of double braces "{{}}", but i dare to suggest something like:

`{^{if expr1 tmpl='#ifTmpl'}{else expr2 tmpl='#else2Tmpl'}}`


> You can achieve the `{for Players head="#caption" tmpl='#player'
empty='#caption_empty'}`
> scenario using `{for Players tmpl='#player'}{else
tmpl='#caption_empty'}`
> where the #player template includes the header
> #caption block: `{{if !index tmpl='#caption'/}}`.

it is quite a traditional approach which i call "ugly"
because it interferes with the tmpl's body, making it _irregular_, therefore, should you read the code "from-top-to-bottom" and encounter a "for", you expect a regularly repeated pattern, which is a mistake, so that code reading becomes increasingly complicated (destroys your intuitive expectations) and requires much longer stack in you brains.

also it mirrors the imperative pseudo-code:

```
for Players do
  if (!index)
    A
  else
    B
end for
```
where the condition will be checked on every entry,
while it is actually needed just once.
(it doesn't look like an "obvious" programming)


> Similarly for things like odd/even

yes. in the case of odd/even this traditional approach is the best (from every perspective).


the _typical_ data-array to text transformation in my opinion looks like the following:

```
if Data is not empty
  print Head
  i:=1;
  loop
    print Data[i]
    i++;
    exit if no more Data
    print Delimiter
  end loop
else
  print Empty
end if
```

NOTE: the exit condition in the middle!

I have been coding this procedure countless times in very many ways,
needless to say it was never plain and compact, despite it always remains the same -- no variations.

over time I have developed idiosyncrasy to delimiters (particularly those that are not allowed to be leading or trailing in a list).

**Comment by BorisMoore** [comment]
On 
> please, avoid HTML-like quasi-parenthesis constructed of individual tags that have a meaning of braces

Well this is fundamental to the declarative tag-based approach of JsRender and JsViews. Containement is central to the approach. Note that the most common style is not to use tmpl=... but to use inline blocks as sub-templates - rather than dereferencing/modularising them to point to independent externally defined templates.

```
{{if foo}}
    {{:name1}} (this will be output if foo is true)
{{else bar}}
    {{:name2}} (this will be output if foo is false and bar is true) 
{{else}}
    {{:name3}} (this will be output if foo and bar are false) 
{{/if}}
```

The use of a {{for}} with a header block will generally be achieved as follows

```
this is the header
{{for items}}
    this is an item
{{else}}
    there were no items
{{/for}}
```

Note also with custom tags, you might have:

```
{{tabs caption="one"}}
    {{:name1}} (this will be output as the first tab)
{{else caption="two"}}
    {{:name2}} (this will be output as the second tab) 
{{else caption="three"}}
    {{:name3}} (this will be output as the third tab) 
{{/if}}
```

Example: http://www.jsviews.com/#samples/tag-controls/tabs

Here is another example of a custom grid view, showing rich nesting of tags:
http://jsfiddle.net/BorisMoore/uu7opr3z/

**Comment by eugene-panferov** [comment]
now I have got an idea why I have slipped so rapidly into using "data-link" only -- seems to me the strictest and the purest way of coding things declaratively.

**Comment by eugene-panferov** [comment]
anyway, not having for-else does not make the software unusable -- it is 
way more usable now than anything i have ever seen

**Comment by BorisMoore** [comment]
I  actually think that the data-link approach rather than the tag approach forces you to add HTML elements in your page to wrap text output in a way that should not be necessary. I would like to be able to output `{^{:name}}` or `{^{if foo}}yes{{/if}}` without being forced to include a `<span>` (say) to wrap those bits of dynamic text.

I actually have implemented the support for for-else in data-link - as `data-link="{if expr1 tmpl='#ifTmpl'}{else expr2 tmpl='#else2Tmpl'}{else expr3 tmpl='#else3Tmpl'}{else tmpl='#noneTmpl'}"`.

It should be included in the next update...

**Comment by BorisMoore** [comment]
This is implemented in the last update. (Commit 62). Here is a jsfiddle example... http://jsfiddle.net/BorisMoore/Lerwt6ya/
