### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by organic-scholar** [BorisMoore/jsviews#294]
jQuery is hardcoded dependency of jsviews. Can i use zepto as an alternative to jQuery?

**Comment by BorisMoore** [comment]
Unfortunately, no.  Zepto does not include all the features of jQuery that are used by JsViews. For example, JsViews uses the jQuery $.event.special feature to track all elements that are removed from the DOM - in order to dispose of data-link bindings on those elements. Zepto does not implement Zepto.event.special in its events module, (or, as far as I know, in any additional modules.)

**Comment by organic-scholar** [comment]
Ok i got it thanks.
