### ISSUE TITLE
redundant linebreaks in the product of a "for" statement

### ISSUE THREAD

**Issue by eugene-panferov** [BorisMoore/jsviews#309]
i have noticed that: &lt;div data-link="{for Obj tmpl="#tmpl"}"&gt;&lt;/div&gt;
produces something like:
&lt;div&gt;
&lt;script&gt;...&lt;/script&gt;
#tmpl's body
&lt;script&gt;...&lt;/script&gt;
#tmpl's body
&lt;script&gt;...&lt;/script&gt;
#tmpl's body
&lt;/div&gt;

which puts an amount of linebreaks within the div's text element.
and linebreaks (shame on html authors!) have SIZE.
so that creating unnecessary intervals between the "#tmpl" elements in the on-screen presentation.

may i ask you to exclude linebreaks from the produced text element,
either by commenting them out, or putting inside these script tags. 

something like the following:
&lt;div&gt;&lt;!--
--&gt;&lt;script&gt;...&lt;/script
&gt;#tmpl's body
&lt;script&gt;...&lt;/script
&gt;#tmpl's body
&lt;script&gt;...&lt;/script
&gt;#tmpl's body&lt;!--
--&gt;&lt;/div&gt;

**Comment by BorisMoore** [comment]
If your template `#tmpl` does not include line breaks:

```
<script id="tmpl" type="text/x-jsrender">templatebody</script>
```

then the innerHTML of your `<div data-link="{for someArray tmpl="#tmpl"}"></div>`  should be:

```
<script type="jsv#2_"></script><script type="jsv#3_"></script>templatebody<script type="jsv/3_"></script><script type="jsv#4_"></script>templatebody<script type="jsv/4_"></script><script type="jsv#5_"></script>templatebody<script type="jsv/5_"></script><script type="jsv/2_"></script>"
```

No line breaks - works for me.

OTOH if you include line breaks in the template:

```
<script id="tmpl" type="text/x-jsrender">
templatebody
</script>
```

they will be preserved. 

Note that the template is the full innerHTML of the template. No whitespace trimming... Since you may actually want, for example, a single linebreak as your template:

```
<script id="tmpl" type="text/x-jsrender">
</script>
```

**Comment by eugene-panferov** [comment]
thanx for the explanation. works for me too!
