### ISSUE TITLE
simple dynamic data-link value

### ISSUE THREAD

**Issue by ethar1** [BorisMoore/jsviews#345]
Dear Boris, 
Thanks for your great work "jsviews" , I like it so much ...
could you please tell me why this not working?
```
{{props #data}}
<span>{{:key}} :</span>: <input data-link="{{:key}} trigger=true">
{{/props}}
```
I already know about 
http://jsfiddle.net/BorisMoore/hqy06tm5/
but its very cokplecated for my case, my case not a full dynamic...
Thanks

**Comment by BorisMoore** [comment]
Hi Ethar,
If you look at the third sample of http://www.jsviews.com/#jsvpropstag you have this:

```
{^{props members}}
  <li>
    <input data-link="prop"/>
    {^{>prop}} ...
  </li>
  ...
```

In your case 

```
{{props #data}}
<span>{{:key}} :</span>: <input data-link="prop">
{{/props}}
```

should work fine - for dynamically changing the property value.

As explained in that topic: 

> Inside the {^{props members}} tag, a block is rendered for each property, with as data context:
> 
> `{key: propertyName, prop: propertyValue}`
> – so {{>key}} gives the key and {{>prop}} gives the value for that property.
> 
> Within the `{^{props}}` the current data item is an object 

In your code you have `<input data-link="{{:key}} trigger=true">` which will render as `<input data-link="keyValue trigger=true">` - but the current context is not the outer #data object, so that will not work.

**Comment by ethar1** [comment]
Thank you very much it work as expected...
