### ISSUE TITLE
custom converter html encoding

### ISSUE THREAD

**Issue by ainglese** [BorisMoore/jsviews#392]
Hi,i've a custom converter witch should output raw html, but the output of the converter gets html-encoded. i can't find any documentation if this is by design and how to avoid that. 
```js
//pseudocode
$.views.converters({
	_f:function(val){ return "€" + "&nbsp;" + val; }
});
```

```html
<span data-link="{_f:amount}"></span>
//the output is €&nbsp;1234
```

**Comment by BorisMoore** [comment]
I'm travelling at the moment so can't reply until after returning on the 20th

**Comment by BorisMoore** [comment]
Yes, it is by design: the default data-linking target is innerText - so it HTML encoded by default.

See the following topics:
- http://www.jsviews.com/#link-text-html
- http://www.jsviews.com/#link-tags
- http://www.jsviews.com/#linked-elem-syntax
  - A data-linked span element (data binding to innerText – default target)
  - The default target for most elements is innerText, but for input and select elements it is value.
  - &lt;div data-link="{:name}">&lt;/div> (one-way binding to innerText – default target attrib – so automatically HTML encodes)

So with your converter, you can choose the `html` target:

    <span data-link="html{_f:amount}"></span>

**Comment by ainglese** [comment]
ok, so the encoding is done on the default binding to innerText, i was assuming it was being done in the converter.  now it's clear, thank you!
