### ISSUE TITLE
'~' operator in templates

### ISSUE THREAD

**Issue by Mytia** [BorisMoore/jsviews#403]
As I understand the first '~' operator is ignored.
It also does not work correctly for object properties without brackets.

https://jsfiddle.net/nq4372t8/68/

**Comment by BorisMoore** [comment]
Hi Mytia.

Yes, that is true - the ~ operator is not supported in template expressions. But here is a possible update, which could support it. 

[jsviews.js.txt](https://github.com/BorisMoore/jsviews/files/2006340/jsviews.js.txt)

How does that work for you?

I'm not sure what you mean by _It also does not work correctly for object properties without brackets._. Can you give an example?

**Comment by Mytia** [comment]
New version works fine.
I just mean that ~(x) works but ~x don't (without space).
~ ~x can be breaking after templates minification, so in production better to use brackets.

**Comment by BorisMoore** [comment]
Yes ~x is assumed to be a helper. To use the ~ operator on a non-helper path such as x, you need to write ~ x or ~(x).

`~ ~x` shouldn't break on minification since it is not within javascript code. It is within the template, so either a string (of HTML markup) or within a script block. In both cases, white-space is preserved. And the compiled template will not include that `~ ~x` string, and should minify fine...

**Comment by BorisMoore** [comment]
This has been fixed in [release v0.9.91](https://github.com/BorisMoore/jsviews.com/commit/f59020fca27090c7e1d948fc82101ad99d662958).
