### ISSUE TITLE
minus character '-' in tag property names

### ISSUE THREAD

**Issue by johan-ohrn** [BorisMoore/jsviews#413]
Is it by design that minus character cannot be used in tag property names? Such as `{{mytag some-property="value" /}}`

My specific problem is I have a custom tag named date that simply wraps an input element with some logic.
I'm trying to "pass through" properties on the tag as attributes in the wrapped input element.
I.e. `{{date data-some-stuff="value" /}}` should render `<input type="text" data-some-stuff="value">`
This allows the consumer of the date tag to have some control over it. Specifically I want to add validation attributes to the input element.

I created this short [fiddle](https://jsfiddle.net/4g3d06t1/) to demonstrate the problem. Look in the developer console to see the error.

I found the following topics discussing rendering/linking to properties with minus in their names:
[311](https://github.com/BorisMoore/jsviews/issues/311), [146](https://github.com/BorisMoore/jsrender/issues/146)
It's not really the same but it's as close as I could find.

**Comment by BorisMoore** [comment]
It is by design, yes. In HTML markup attribute values are not expressions, but strings wrapped in quotes

    <input data-foo="sss"/>

And so the above is fairly easy to 'parse' (by the human eye)

But JsRender markup accepts both named and unnamed paramters, as well as contextual paramters, and all accept expressions, as in

    {{mytag x-4 foo=a-3 ~bar=b-1}}

This is more powerful, but it is not so easy understand the semantics (parse)

If you allow the following it gets very confusing

    {{mytag x-4 b-1=a-3}}

And if you allow that, will you also allow:

    {{mytag x-4 b-1=a-3 ~y-6-z=44}}

If you do, then what will this render:

    {{if true ~y=10 ~y-4="aa"}}{{:~y-4}}{{/if}}

It is ambiguous, and could render as `6` or as `aa`

For your  scenario, can you accept a specific syntax such as `{{mytag some$property$foo="value" /}}` or 
`{{mytag somePropertyFoo="value" /}}`, and then write code to map the above to `<input some-property-foo="value"/>`?

**Comment by johan-ohrn** [comment]
(Sorry about the very late response. I've been really busy)

When you put it like this I agree with your reasoning and the proposed solution using a special syntax is a good idea.

I might suggest though that this is somehow expressed in the documentation at jsviews.com. Perhaps under the Custom Tags topic?

**Comment by BorisMoore** [comment]
Yes, I'll update the *Note:...* in [this section](https://www.jsviews.com/#search?s=note%3a%20tag%20property%20names%20can%20include&l=tagsapi@0).
