### ISSUE TITLE
Observing length of checked checkboxes

### ISSUE THREAD

**Issue by Dissolubilis** [BorisMoore/jsviews#435]
Hello
I need to know how much data-linked checkboxes are checked, however its length doesn't change on any checkbox checking. Example -  https://jsfiddle.net/egmk875o/  .
Is there anything I can do to make it work?

**Comment by BorisMoore** [comment]
When the user modifies the selection of checked checkboxes, the data property is observably replaced by a new array. This means that in order to observe the length of the array, you need to use a [deep path](https://www.jsviews.com/#linked-paths@deep), such as `{^{:checked^length}}` in your example.

**Comment by Dissolubilis** [comment]
Thank you, it works like charm now! (fixed example https://jsfiddle.net/15aj2tq0/)
