### ISSUE TITLE
Using a tmpl selector that begins with a # but is not an ID selector does not work

### ISSUE THREAD

**Issue by nfplee** [BorisMoore/jsviews#455]
Please see the following JSFiddle:

https://jsfiddle.net/p5urz4ey/

This works fine if you change the version to 1.0.10.

**Comment by BorisMoore** [comment]
Thanks for calling this out, Lee. I have a fix, which I will share with you in the coming days...

**Comment by BorisMoore** [comment]
You can test my proposed fix, using this updated version of jsviews.js:

[jsviews1013.js.txt](https://github.com/BorisMoore/jsviews/files/10452400/jsviews1013.js.txt)

It has line  1125:
`				} if (!elem && $.fn && !$sub.rTmpl.test(value)) {`
which replaces the previous version:
`				} else if ($.fn && !$sub.rTmpl.test(value)) {`

Let me know if this works for you.
Thanks

**Comment by nfplee** [comment]
Thanks yeah that seems to do the trick.

**Comment by BorisMoore** [comment]
To explain this issue:

The JSFiddle linked above includes the line:
`<tbody data-link="{for people tmpl='#people .item-template'}"></tbody>`

It loads the template under the script element with class `"item-template"`, which is itself a descendant of the element (in fact a `<div>`) which has ID `"people"`.

The selector `'#people .item-template'` - a "descendant selector" starts with a `'#'`, and the previous JsRender code assumed that a selector starting with a `'#'` is an "ID selector". However the presence of white space in the selector means that it is not a valid "ID selector" and is in fact a "descendant selector". The bug fix ensures that JsRender no longer assumes that a selector starting with `"#"` is an "ID selector", and instead interprets the selector correctly, and so loads the correct template in the JSFiddle example.

The issue is with JsRender as well as with JsViews (which uses JsRender)

**Comment by BorisMoore** [comment]
Resolved in release v1.0.13
